export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="norm"

plugins=(git, vi-mode, aws)

# User configuration

export PATH="/home/derrick/bin:/home/derrick/.local/bin:$PATH"

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR=vim

if whence dircolors >/dev/null; then
  eval `dircolors ~/.dircolors/dircolors.256dark`
else
  export CLICOLORS=1
  export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
fi
