export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="norm"

plugins=(git, vi-mode, aws)

bindkey -v

export PATH="/home/derrick/bin:/home/derrick/.local/bin:$PATH"

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR=vim

export ERL_AFLAGS="-kernel shell_history enabled"

if whence dircolors >/dev/null; then
  eval `dircolors ~/.dircolors/dircolors.256dark`
else
  export CLICOLORS=1
  export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
fi

alias ubuntu_installed_packages="comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -e /home/derrick/.nix-profile/etc/profile.d/nix.sh ]; then . /home/derrick/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

PATH=$PATH:/home/derrick/.local/bin
